local ship = require("ship")

describe("generic actor example", function()
    it("advertises the generic actor contract", function()
        assert.is_true(ship.capabilities.has("actor.spawn"))
        assert.is_true(ship.capabilities.has("actor.destroy"))
        assert.is_true(ship.capabilities.has("actor.exists"))
    end)

    it("spawns an opaque owned handle", function()
        local actor, err = spawn_demo_actor()
        assert.is_nil(err)
        assert.equals("actor", actor.kind)
        assert.is_true(actor.generation > 0)
        assert.is_true(actor.scene_generation > 0)
        assert.is_nil(actor.game)
        assert.is_nil(actor.pointer)
        local alive, exists_err = ship.actor.exists(actor)
        assert.is_true(alive)
        assert.is_nil(exists_err)
    end)

    it("replaces the previous actor without exceeding the manifest limit", function()
        local first = spawn_demo_actor()
        local second, err = spawn_demo_actor()
        assert.is_nil(err)
        assert.is_true(second.generation >= first.generation)
        local first_alive, first_err = ship.actor.exists(first)
        assert.is_false(first_alive)
        assert.is_nil(first_err)
    end)

    it("uses the K hotkey", function()
        assert.equals(1, mock.input.press("K"))
    end)
end)
